- hosts: all
  name: Hello
  tasks:
    - name: hello task
      command: "echo 'Hello there!'"

- name: IX confs setup
  hosts: squawk_targets
  roles:
    - ix-confs

- name: a bad task
  hosts: hk
  tasks:
    - name: a bad task
      fail:
        msg: "whoops"
