- hosts: all
  name: Execute squawk play
  tasks:
    - name: hello task
      command: "echo 'Hello there!'"

- hosts: squawk_targets
  name: Roll out ix-confs files
  tasks:
    - import_roles: ix-confs
